# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74e0e7ccbf76b94ab9b560cf876ecc5b4ecd06e08cef5a6c6aeba9759d6225d89697e2c801cc33ac82b29da8a369778f9a7708fcced81200eb61a5ced2c92079

test:
  secret_key_base: 8de218b57c03acbf8f94a0bf9b294bdeecae362c51c26da2bddf78abc36c4b2f0e3908f1577a86d02f35413d44e1fd348f6a04eeae9d7fd85e3ae68326d32714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
